<?php echo $head; ?>

<div class="lette-logo"></div>
<div class="login-message">Por favor, efetue o login.</div>
<div class="login-container">
		<form action="<?php echo BASE_URL; ?>default/login/login" method="post" id="login-access" onsubmit="login();">
				<div class="uid-section">
						<div class="mask"></div>
						<input type="text" name="login_uid" value="LOGIN" title="Teste" />
				</div>
				<div class="pwd-section">
						<div class="mask"></div>
						<input type="password" name="login_pwd" value="senha" />
						<input type="submit" name="login_smt" value="" />
				</div>
		</form>
</div>